# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Check if app is buildable

on:
  push:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    environment: dev
    # env :
    #   DATABASE_URL: ${{ secrets.DATABASE_URL }}
    #   PORT: ${{ secrets.PORT }}
    #   HOST :  ${{ secrets.HOST }}
    #   POSTMARK_API_KEY: ${{ secrets.POSTMARK_API_KEY }}
    #   POSTMARK_SENDER: ${{ secrets.POSTMARK_SENDER }}
    #   POSTMARK_REPLYTO: ${{ secrets.POSTMARK_REPLYTO }}
    #   COOKIE_KEY: ${{ secrets.COOKIE_KEY }}
    #   MAIL_KEY :  ${{ secrets.MAIL_KEY }}
    #   ACCESS_EXPIRE: ${{ secrets.ACCESS_EXPIRE }}
    #   REFRESH_EXPIRE: ${{ secrets.REFRESH_EXPIRE }}
    #   FIRSTSTEP_EXPIRE: ${{ secrets.FIRSTSTEP_EXPIRE }}
    #   VALIDATION_TOKEN_EXPIRE: ${{ secrets.VALIDATION_TOKEN_EXPIRE }}
    #   BASE_URL_BACKOFFICE :  ${{ secrets.BASE_URL_BACKOFFICE }}
    #   ALLOWED_ORIGINS :  ${{ secrets.ALLOWED_ORIGINS }}
    #   S3_ACCESS_KEY_ID :  ${{ secrets.S3_ACCESS_KEY_ID }}
    #   S3_SECRET_ACCESS_KEY :  ${{ secrets.S3_SECRET_ACCESS_KEY }}
    #   BUCKET_NAME :  ${{ secrets.BUCKET_NAME }}
    #   LOGS_BUCKET_NAME :  ${{ secrets.LOGS_BUCKET_NAME }}
    #   LEMONWAY_API_KEY : ${{ secrets.LEMONWAY_API_KEY }}
    #   LEMONWAY_BASE_URL :  ${{ secrets.LEMONWAY_BASE_URL }}
    #   LEMONWAY_URL_AUTH :  ${{ secrets.LEMONWAY_URL_AUTH }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js version 18
        uses: actions/setup-node@v3
        with:
            node-version: '18'
      - run: npm i
      # - run: npx prisma db push --accept-data-loss
      - run: tsc
      - run: mkdir content content/logs
      - run: touch content/logs/pino-logs.log
      - run: npm run test